converting an array to a DataFrame usually means taking data stored in a NumPy array and putting it into a Pandas DataFrame so that it becomes easier to analyze, filter, clean, and visualize.

1. Simple 1D array

In [1]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30, 40, 50])

df = pd.DataFrame(arr, columns=["Marks"])

print(df)

   Marks
0     10
1     20
2     30
3     40
4     50

Here:

    arr → NumPy array
    pd.DataFrame() → converts it into a DataFrame
    columns=["Marks"] → gives the column name
    0, 1, 2... → Pandas automatically creates the index

2. 2D array

This is very common in Machine Learning.

In [2]:
arr = np.array([
    [25, 50000],
    [30, 60000],
    [35, 70000]
])

df = pd.DataFrame(arr, columns=["Age", "Salary"])

print(df)

   Age  Salary
0   25   50000
1   30   60000
2   35   70000

  Think of the array like this:

          Age    Salary
          ↓       ↓
        [25,    50000]
        [30,    60000]
        [35,    70000]

  The DataFrame adds meaningful column names and an index.

3. Why convert an array to DataFrame?

    A NumPy array:

In [3]:
arr = np.array([
    [25, 50000],
    [30, 60000],
    [35, 70000]
])

In [5]:
df = pd.DataFrame(arr, columns=["Age", "Salary"])

In [6]:
df["Age"]

0    25
1    30
2    35
Name: Age, dtype: int64

In [7]:
df[df["Salary"] > 55000]

   Age  Salary
1   30   60000
2   35   70000

In [8]:
df.describe()

        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

In [9]:
df.head()

   Age  Salary
0   25   50000
1   30   60000
2   35   70000

So the basic idea is:

NumPy Array → Pandas DataFrame → Data Analysis / Machine Learning

4. Important example in ML

Suppose you have predictions from a model:

In [10]:
predictions = np.array([45000, 52000, 61000, 70000])

You can convert them to a DataFrame:

In [11]:
predictions_df = pd.DataFrame(
    predictions,
    columns=["Predicted_Salary"]
)

print(predictions_df)

   Predicted_Salary
0             45000
1             52000
2             61000
3             70000

    Remember

    The most important syntax is:

    pd.DataFrame(array)

    or, with column names:

    pd.DataFrame(array, columns=["Column1", "Column2"])

    Array = raw numerical structure
    DataFrame = tabular structure with rows and columns.

converting a 2D NumPy array into a Pandas DataFrame.

In [12]:
import numpy as np
import pandas as pd

marks = np.array([[11,22,33],[44,55,66]])

df = pd.DataFrame(
    marks,
    columns=['Subject1', 'Subject2', 'Subject3']
)

print(df)

   Subject1  Subject2  Subject3
0        11        22        33
1        44        55        66

    NumPy Array
        ↓
    [[11,22,33],
    [44,55,66]]
        ↓
    pd.DataFrame()
        ↓
    Pandas DataFrame
        ↓
    Subject1  Subject2  Subject3
      11        22        33
      44        55        66

Key syntax to remember:

df = pd.DataFrame(array, columns=['Column1', 'Column2', 'Column3'])

This example is the same Array → DataFrame conversion, but now it also assigns custom row/index names.

The important new part is:

index=['Anu', 'John']

In [13]:
import numpy as np
import pandas as pd

marks = np.array([[11,22,33],[44,55,66]])

df = pd.DataFrame(
    marks,
    columns=['Subject1', 'Subject2', 'Subject3'],
    index=['Anu', 'John']
)

print(df)

      Subject1  Subject2  Subject3
Anu         11        22        33
John        44        55        66

    What does index mean?

    Normally, Pandas automatically gives row numbers:

      Subject1  Subject2  Subject3
    0         11        22        33
    1         44        55        66

    But here:

    index=['Anu', 'John']

    you are telling Pandas:

    "Instead of 0 and 1, use Anu and John as the row labels."

    So:

    Array                         DataFrame

    [11, 22, 33]       →          Anu   →  11  22  33
    [44, 55, 66]       →          John  →  44  55  66

    Remember these 3 parameters
    pd.DataFrame(
        marks,
        columns=['Subject1', 'Subject2', 'Subject3'],
        index=['Anu', 'John']
    )

    | Parameter | Purpose      |
    | --------- | ------------ |
    | `marks`   | Data/array   |
    | `columns` | Column names |
    | `index`   | Row names    |


    Simple memory trick:

    columns → names for columns
    index → names for rows

This Example 2 is a little more advanced because the array contains different

types of data: names, ages, birth years, and graduation years.

In [14]:
import numpy as np
import pandas as pd

student_details = np.array([
    ['Jon', 25, 1995, 2016],
    ['Maria', 47, 1973, 2000],
    ['Bill', 38, 1982, 2005]
], dtype=object)

df = pd.DataFrame(
    student_details,
    columns=['Name', 'Age', 'Birth Year', 'Graduation Year']
)

print(df)

    Name Age Birth Year Graduation Year
0    Jon  25       1995            2016
1  Maria  47       1973            2000
2   Bill  38       1982            2005

    1. Creating the NumPy array
    student_details = np.array([
        ['Jon', 25, 1995, 2016],
        ['Maria', 47, 1973, 2000],
        ['Bill', 38, 1982, 2005]
    ], dtype=object)

    The data looks like a table:

    Name     Age    Birth Year    Graduation Year
    Jon      25        1995             2016
    Maria    47        1973             2000
    Bill     38        1982             2005

    There are:

    3 rows → 3 students
    4 columns → Name, Age, Birth Year, Graduation Year
    2. Why dtype=object?

    This is important.

    The array contains both:

    'Jon'      → string
    25         → integer
    1995       → integer
    2016       → integer

    So the array contains different data types.

    By specifying:

    dtype=object

    we tell NumPy:

    "Allow each element to keep its own Python data type."

    3. Convert Array → DataFrame
    df = pd.DataFrame(
        student_details,
        columns=['Name', 'Age', 'Birth Year', 'Graduation Year']
    )

    Here:

    student_details
          ↓
      NumPy array
          ↓
    pd.DataFrame()
          ↓
      DataFrame

    The columns parameter gives names to the four columns.

    4. Output
        Name  Age  Birth Year  Graduation Year
    0    Jon   25        1995             2016
    1  Maria   47        1973             2000
    2   Bill   38        1982             2005

    Notice that Pandas automatically creates:

    0
    1
    2

    as the row/index values because we didn't provide a custom index.

    5. Why is this useful?

    Once the data is a DataFrame, you can easily perform operations such as:

    df['Name']

    Get only the names.

    df['Age']

    Get the ages.

    df[df['Age'] > 30]

    Get students whose age is greater than 30.

    df.shape

    Output:

    (3, 4)

    Meaning 3 rows × 4 columns.

    One easy trick to remember

    Quotes → String

    "Jon"
    "Chennai"
    "25"

    No quotes + whole number → Integer

    25
    100
    1995

    And with decimal:

    25.5

    that is a Float, not an Integer.

This example is teaching you how **to check the DataFrame type and the data type of each column**

In [15]:
import numpy as np
import pandas as pd

student_details = np.array([
    ['Jon', 25, 1995, 2016],
    ['Maria', 47, 1973, 2000],
    ['Bill', 38, 1982, 2005]
], dtype=object)

df = pd.DataFrame(
    student_details,
    columns=['Name', 'Age', 'Birth Year', 'Graduation Year']
)

print(df)
print(type(df))
print(df.dtypes)

    Name Age Birth Year Graduation Year
0    Jon  25       1995            2016
1  Maria  47       1973            2000
2   Bill  38       1982            2005
<class 'pandas.core.frame.DataFrame'>
Name               object
Age                object
Birth Year         object
Graduation Year    object
dtype: object

    Name               object
    Age                object
    Birth Year         object
    Graduation Year    object
    dtype: object

    Why object?

    Because NumPy stored the mixed data ("Jon", 25, 1995, etc.) as an object-type array.

The better Pandas approach

If you want the columns to have their proper types, create the DataFrame and then convert the numeric columns:

In [17]:
df['Age'] = df['Age'].astype(int)
df['Birth Year'] = df['Birth Year'].astype(int)
df['Graduation Year'] = df['Graduation Year'].astype(int)

In [18]:
print(df.dtypes)

Name               object
Age                 int64
Birth Year          int64
Graduation Year     int64
dtype: object

    Now:

    Name → object (text)
    Age → int64 (integer)
    Birth Year → int64 (integer)
    Graduation Year → int64 (integer)

    ----

    Age, Birth Year, and Graduation Year are integer columns, using 64-bit representation.

    ----

    int32 vs int64

    Both are integers:

    int32 → integer stored using 32 bits
    int64 → integer stored using 64 bits

    ----

    What does 64 mean?

    The 64 means 64 bits of computer memory are used to store each integer value.

    A bit is a tiny unit of computer information that can be either:

    0 or 1

    So:

    64 bits = 64 binary positions

| Data type | Meaning                            |
| --------- | ---------------------------------- |
| `int64`   | Integer, 64-bit                    |
| `float64` | Decimal number, 64-bit             |
| `object`  | General Python objects, often text |
| `bool`    | True / False                       |

This example is teaching a very important Pandas concept:

How to add a NumPy array as a new column to an existing DataFrame.

In [19]:
import numpy as np
import pandas as pd

#create pandas DataFrame
df = pd.DataFrame({
    'Game1': [25, 12, 15, 14, 19, 23, 25, 29],
    'Game2': [5, 7, 7, 9, 12, 9, 9, 4],
    'Game3': [11, 8, 10, 6, 6, 5, 9, 12]
})

#create NumPy array for 'Game4'
Game4 = np.array([2, 3, 1, 0, 2, 7, 8, 2])

#add 'Game4' array as new column in DataFrame
df['Game4'] = Game4.tolist()

#display the DataFrame
print(df)

   Game1  Game2  Game3  Game4
0     25      5     11      2
1     12      7      8      3
2     15      7     10      1
3     14      9      6      0
4     19     12      6      2
5     23      9      5      7
6     25      9      9      8
7     29      4     12      2

| Code                                         | Explanation                                                        |
| -------------------------------------------- | ------------------------------------------------------------------ |
| `import numpy as np`                         | Imports the **NumPy** library and gives it the short name `np`.    |
| `import pandas as pd`                        | Imports the **Pandas** library and gives it the short name `pd`.   |
| `#create pandas DataFrame`                   | Comment explaining that we are going to create a Pandas DataFrame. |
| `df = pd.DataFrame({...})`                   | Creates a **Pandas DataFrame** and stores it in the variable `df`. |
| `'Game1': [25, 12, 15, 14, 19, 23, 25, 29]`  | Creates the **Game1 column** with 8 values.                        |
| `'Game2': [5, 7, 7, 9, 12, 9, 9, 4]`         | Creates the **Game2 column** with 8 values.                        |
| `'Game3': [11, 8, 10, 6, 6, 5, 9, 12]`       | Creates the **Game3 column** with 8 values.                        |
| `Game4 = np.array([2, 3, 1, 0, 2, 7, 8, 2])` | Creates a **NumPy array** called `Game4` containing 8 values.      |
| `df['Game4']`                                | Refers to a column named **Game4** in the DataFrame.               |
| `=`                                          | Assigns a value to the `Game4` column.                             |
| `Game4.tolist()`                             | Converts the NumPy array into a **Python list**.                   |
| `df['Game4'] = Game4.tolist()`               | Adds the `Game4` values as a **new column** in the DataFrame.      |
| `print(df)`                                  | Displays the complete DataFrame.                                   |


------

| Step | What happens                                      |
| ---- | ------------------------------------------------- |
| 1    | Import NumPy                                      |
| 2    | Import Pandas                                     |
| 3    | Create DataFrame with `Game1`, `Game2`, `Game3`   |
| 4    | Create NumPy array called `Game4`                 |
| 5    | Convert `Game4` array to a list using `.tolist()` |
| 6    | Add it as a new `Game4` column                    |
| 7    | Print the final DataFrame                         |